---
title: "パブリケーション"
---

## 著書・共著
- 長縄久生・椎名乾平・川崎惠里子（編）『認知心理学の視点』p.59-74 ナカニシヤ出版　1997
- 牧野達郎（編）『知覚の可塑性と行動適応』p153-167 ブレーン出版　1998
- 鬢櫛一夫『両眼立体視における対応問題の研究』心理学モノグラフ　1999
- 原島博（監修） 元木紀雄・矢野澄雄（編）『3 次元画像と人間の科学』p1-19，オーム社　2000

## 学術論文
- Bingushi, K. & Yukumatsu, S. Disappearance of a monocular image in Panum’s limiting case. Japanese Psychological Research, 47(3),223-229, 2005.
- Sainio, M., Hyona, J, Bingushi, K. & Bertram, R. The role of interword spacing in reading Japanese: An eye movement study. Vision Research, 47, 2575-2584, 2007.
- Takase, S., Yukumatsu, S., & Bingushi, K. Local binocular fusion is involved in global binocular rivalry. Vision Research, 48, 1798-1803, 2008.
- Takase, S., Yukumatsu, S & Bingushi, K. Recovery from perceptual filling-in is gated by interocular matching. Vision Research, Vision Research, 49, 1909-1915, 2009
- Takase, S., Yukumatsu, S. & Bingushi, K. Perceptual dominance during binocular rivalry is prolonged by a dynamic surround. Vision Research, 53, 1798-1803, 2013
- 小澤良・鬢櫛一夫　両眼固視中の片眼におけるコントラスト感度の低下　心理学研究，83，536-545, 2013